### ISSUE TITLE
Distance between two 2D matrix

### ISSUE THREAD

**Issue by jnaranjo-sciling** [wannesm/dtaidistance#109]
Hi community, 
I am trying to obtain the distance between two matrices. I have implemented the following code:

```
series = [a,b]
ds =  dtw.distance_matrix_fast(series)
```

where `a` and `b` are matrices of M x N dimension.

I am getting the following error:

```
The compiled dtaidistance C-OMP library is not available.
See the documentation for alternative installation options.
Traceback (most recent call last):
  File "/snap/pycharm-community/226/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "anaconda3/envs/dtaidistance/lib/python3.6/site-packages/dtaidistance/dtw.py", line 669, in distance_matrix_fast
    _check_library(raise_exception=True, include_omp=parallel)
  File "anaconda3/envs/dtaidistance/lib/python3.6/site-packages/dtaidistance/dtw.py", line 93, in _check_library
    raise Exception(msg)
Exception: The compiled dtaidistance C-OMP library is not available.
See the documentation for alternative installation options.
```
Is not possible to obtain this value using this implementation? 

Thanks in advance

**Comment by wannesm** [comment]
Hi, we recently started triggering an exception if the library is compiled without OMP (for C parallelization). This is probably because at compile-time the OMP library was not available on your system. You can force the method to use multiprocessing using `use_mp=True`.

This might be confusing, so I have now changed the implementation back such that it automatically changes to the multiprocessing option if OMP is not detected.

**Comment by jnaranjo-sciling** [comment]
Now I am getting this error:
```
dist = dtw.distance_matrix_fast(s, use_mp=True)
TypeError: distance_matrix_fast() got an unexpected keyword argument 'use_mp'
```
Where do I have to indicate `use_mp=True`?

**Comment by wannesm** [comment]
If it's not yet available in your version, you can use `distance_matrix` directly with `use_c=True, parallel=True, use_mp=True`.
