### ISSUE TITLE
`warping_path` for `dtaidistance.dtw.distance_matrix`

### ISSUE THREAD

**Issue by flipdazed** [wannesm/dtaidistance#137]
Thanks for this amazing library. Is there a way in which we can back out the `warping_path` that corresponds to each result from the results of `distance_matrix` without doing all combinations for `dtaidistance.dtw.warping_path`?

**Comment by wannesm** [comment]
You will need to run `warping_path` for each comparison because `distance_matrix` uses a compact datastructure for the `distance` computations that only stores what is necessary to compute the distance. But this datastructure does not allow to reconstruct the warping path (which is more expensive wrt memory).

If you are computing all pairwise comparisons, this functionality is easily obtained with:

```
dist_opts = {'window': 10}  # options you want to pass to DTW
idxs = np.triu_indices(len(s), k=1)  # upper triangular matrix indices
for c, r in zip(*idxs):
    wp = dtw.warping_path(s[r], s[c], **dist_opts)
    print(wp)
```

And if you want to parallelize, you can replace the for-loop with a `multiprocessing.Pool`.
