### ISSUE TITLE
Import Error: ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by ankitk2109** [wannesm/dtaidistance#164]
Hi all,

Seems like the latest update has renamed the file from `dtw_cc_numpy.pyx` ->`util_numpy_cc.pyx` but the import in file` utils.py` remains the same causing an import error. 

![image](https://user-images.githubusercontent.com/26432753/160398932-36317379-c9c6-4f52-99c4-a4278aa4cfb8.png)

Please check the docstring where the filename is mentioned as `dtaidistance.dtw_cc_numpy` however the filename has been changed `to util_numpy_cc.pyx`

Not cent percent sure if this is causing the issue but something the team can look into.

Thanks,
Ankit

**Comment by wannesm** [comment]
This error is typically shown when numpy and dtw are precompiled but from different sources or different numpy versions. Try installing the latest version of numpy. If that does not work, install dtw without precompiled binaries (`--no-binary dtaidistance`) such that it uses the exact version you have installed.

**Comment by ankitk2109** [comment]
I tried pip `install -v --force-reinstall --no-deps --no-binary dtaidistance dtaidistance` but getting the same error. I have the current numpy version dependency on other packages so unfortunately, I can change that. But I will try it separately and do let you know. Thanks

**Comment by LuisBlanche** [comment]
@ankitk2109  I am having the same issue and I think this might be related to the mac m1 platform. I wonder if there is any plan to publish an ARM64 version of the package on either of   -[ https://conda.anaconda.org/conda-forge/linux-aarch64]( https://conda.anaconda.org/conda-forge/linux-aarch64)
 or.  -[ https://conda.anaconda.org/conda-forge/linux-aarch64]( https://conda.anaconda.org/conda-forge/noarch)

**Comment by wannesm** [comment]
Can you also share which line in which file triggers the exception?

Does numpy work when using directly? The compilation does not require a recent numpy version.

We'll look into adding additional architectures to the conda-force prebuilding. And once the VM is available for Github Actions we'll also add it there.

**Comment by Megapiro** [comment]
I am facing the same issue, by trying to import the library in a Jupyter lab in gcp. Tried to upgrade numpy and force reinstall dtaidistance but I always get the same error. I let you here the screenshot:
<img width="629" alt="image" src="https://user-images.githubusercontent.com/48255237/166423056-0f316c1c-5a44-4aba-9eb2-ed1f3a314ab7.png">

**Comment by wannesm** [comment]
In the master branch, `try_import_c` now prints the Numpy version used for compilation and for execution. These be close to each other.

For example:
```
$ pip install -v --no-deps --force-reinstall git+https://github.com/wannesm/dtaidistance
$ python -c "import dtaidistance; dtaidistance.dtw.try_import_c(True)"
All ok ...
== Packages ==
- Numpy version: 1.22.3
...
== Compilation information ==
...
Numpy found (during compilation):
- Version: 1.22.3
```

**Comment by wannesm** [comment]
Thank you for trying. It helps a lot to get this feedback. I overlooked that loading the package already triggers the error. Thus before you can call try_import_c. It is now fixed in the master branch.

I can only replicate the error with a mismatch between numpy versions during and after installation. So it would be interesting to see the output after trying again with the current branch.

If that does not work. Running pip without isolation during build should work better (this uses the numpy package you have installed):
```
pip install -v --force-reinstall --no-deps --no-build-isolation --no-binary dtaidistance  dtaidistance
```

Numpy is indeed not strictly required and can be removed if necessary. The code will then still work with Numpy for simple cases but relies on the Python standard array buffers protocol. The dependency, however, is hardcoded in the pyproject.toml file because most people need it. The dependency can be ignored by removing it from that file and installing from [source](https://dtaidistance.readthedocs.io/en/latest/usage/installation.html#from-source).

**Comment by matanster** [comment]
Thanks so much. Still scratching my head how I got the installation and runtime versions of numpy not be the same one in my venv, which I'll chew on as I'm now made aware of such pip intricacies. 

The install line that you provide above makes it work alongside my current (1.20.03) numpy. 

I think I get the nature of the (weakly) relaxed dependency on numpy, thanks for the clarification about it. I might also guess that there's probably no numpy c api compatibility issue upward of 1.20.03 which is currently known. Thanks for this special library.

**Comment by wannesm** [comment]
Thanks for the feedback. There is indeed a binary incompatibility between Numpy versions 1.20.03 and the current 1.22.3. 

But it's not something you did wrong. Pip installs and compiles packages following the recent package structure guidelines in an isolated environment ([PEP 517](https://peps.python.org/pep-0517/)). In that new environment it downloads the most recent version of Numpy and compiles against that version. Afterwards when you run the package it uses the installed version, which in this case differs too much from the version used for compilation. That's why you need the `--no-build-isolation` argument which uses your current packages instead of a new isolated virtual environment. It took me also some time to figure out.

The test command now prints out both the current and installation version of Numpy to identify this issue more quickly:
```
$ python -c "import dtaidistance; dtaidistance.dtw.try_import_c(verbose=True)"
```

I am going to consider this issue as solved. If this problem still occurs, feel free to add new comments to this issue or reopen it.
