### ISSUE TITLE
Nan Values in the matrices produce empty distance matrix while consuming massive resources

### ISSUE THREAD

**Issue by Ne-oL** [wannesm/dtaidistance#165]
hi,
i tried reaching out in twitter before opening an issue just to be sure, but found no response.

the issue is mainly that if a NaN value was in the input matrix to the dtw distance calculation, the algorithm will work and it seems to be doing all the calculations without producing any errors but the final output is an empty matrix (had the calculation running for days on Workstation). so I'm not sure where the issue lies as the documentation didn't mention anything about it. but I think if it cant process the dataset with NaN it should stop execution early and raise an exception detailing the issue of the NaN values. or if it can it should produce an output of the calculations with the NaN values, though i have no idea if thats possible.

**Comment by wannesm** [comment]
The distance wrt a NaN is again a NaN. While this is expected behavior, I understand the frustration. We try to introduce as few additional loops as possible so we would need to think where and whether we want this extra check to always be executed (numpy also seems to avoid it for norms, but scipy does it for distances). You can already add a `numpy.asarray_chkfinite` before passing the arrays to dtaidistance.

**Comment by Ne-oL** [comment]
Its my mistake for not checking for NaN, the dataset was a bit large (>9) and there apparently were few NaNs hiding somewhere inside. But i wil definitely check for NaN regularly now, i usually check using pandas isna(). I will close the issue now. Thanks for answering.
