### ISSUE TITLE
KMeans do not support ndim series.

### ISSUE THREAD

**Issue by tongda** [wannesm/dtaidistance#179]
According to this [line](https://github.com/wannesm/dtaidistance/blob/559ddb97916fe2314ba39a9714f24e64ce0ecd7e/dtaidistance/clustering/kmeans.py#L261), it seems KMeans support ndim series. However, the [initialization](https://github.com/wannesm/dtaidistance/blob/559ddb97916fe2314ba39a9714f24e64ce0ecd7e/dtaidistance/clustering/kmeans.py#L271) use 1-dim version of distance. As a result, calling `model.fit` will raise exception with n-dim series.

**Comment by wannesm** [comment]
The default initialization (kmeans++) did indeed not yet support ndim series. This is fixed in 32cebdb4ee9dfa9f1dd2be3b19b16114ba415455  and will be part of the next release. If you  already want to use this functionality you can install directly from github using `pip install --force-reinstall --no-binary dtaidistance git+https://github.com/wannesm/dtaidistance.git` (assuming you have a C compiler installed if you want to use the fast version).

**Comment by tongda** [comment]
Thanks, that helps a lot.
