### ISSUE TITLE
How to specify numpy version?

### ISSUE THREAD

**Issue by kilianbr** [wannesm/dtaidistance#71]
Hello, first of all thanks for the fantastic library. I'm using it on windows and now working to transfer my app to a raspberry pi4 running the latest debian buster. 
I'm using python3 and the "normal" installation using 

`pip3 install dtaidistance`
 
is working fine if I have numpy installed before. However if I run my code I've got the exact same error discussed here: #20 . If I try to install the library with the suggested

 `pip install --vvv --upgrade --force-reinstall dtaidistance`

 it doesn't work. I don't want to copy the whole logs, that would be overwhelming but I think because of logs like: _ error: Command "arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g _ or _arm-linux-gnueabihf-gcc: numpy/core/src/multiarray/typeinfo.c_ that dtaidistance is trying to install the arm64 package of numpy. For my pi I need the specific armhf architecture, which I can find here:  [debian python3-numpy](https://packages.debian.org/buster/armhf/python3-numpy/download). 
So what I would need (and possibly some users from #20 ) is to specifiy the place where dtaidistance can find the numpy package (which would be local in my case) to succesfull installing it.

Can you help me? Best regards!

**Comment by kilianbr** [comment]
I tried to install the package from source, which resulted in the following logs:

> root@4pi2:/mnt/dtaidistance-master/dtaidistance-master# python3 setup.py build_ext --inplace
>     running build_ext
>     Using the following environment variables:
> CC=
> CPPFLAGS=
> CFLAGS=
> LDFLAGS=
> Compiler type: unix
> --noopenmp: 0
> Checking for OpenMP availability
> arm-linux-gnueabihf-gcc -dM -E -fopenmp -stdout=-1 input= encoding=ascii
> ... found OpenMP
> building 'dtaidistance.dtw_c' extension
> arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include/python3.7m -c dtaidistance/dtw_c.c -o build/temp.linux-armv7l-3.7/dtaidistance/dtw_c.o -fopenmp
> In file included from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarraytypes.h:1822,
>                  from /usr/lib/python3/dist-packages/numpy/core/include/numpy/ndarrayobject.h:12,
>                  from /usr/lib/python3/dist-packages/numpy/core/include/numpy/arrayobject.h:4,
>                  from dtaidistance/dtw_c.c:619:
> /usr/lib/python3/dist-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
>  #warning "Using deprecated NumPy API, disable it with " \
>   ^~~~~~~
> arm-linux-gnueabihf-gcc: fatal error: Killed signal terminated program cc1
> compilation terminated.
> error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1

I double checked the numpy version and it turns out that the latest debian python3-numpy package is version x.16. From the logs I get that dtaidistance is searching for a version >=x.17. Since the latest version isn't availible for buster at the moment, would there be any handy workaround for that case?

**Comment by wannesm** [comment]
You can manually indicate where the numpy library is installed in the setup.py file by overwriting line 21 `np_include_dirs = [numpy.get_include()]`.

We don't require advanced features from numpy so we haven't specified a minimal version. The error message appears rather that unsupported deprecated features are used. Could you share what's on (and around) line 619 in the generated dtw_c.c file?

By the way, numpy is used because it's a convenient library but it's not crucial. However, it would require a factorisation of the code into pure Python cython code, which is not a quick fix.

**Comment by wannesm** [comment]
The dependency on Numpy is also rather historical and not required. I've pushed the (not yet released) V2 version of the toolbox for which the Numpy dependency is optional. It is probably also a bit faster since it copies less data and has better C parallelization. You can install this version using:

```
pip install git+https://github.com/wannesm/dtaidistance@v2
```
