### ISSUE TITLE
fit() in LinkageTree has no return value

### ISSUE THREAD

**Issue by stardust0083** [wannesm/dtaidistance#75]
```
def fit(self, series):
        self.series = SeriesContainer.wrap(series)
        try:
            from scipy.cluster.hierarchy import linkage
        except ImportError:
            logger.error("The LinkageTree class requires the scipy package to be installed.")
            self.linkage = None
            linkage = None
            return
        dists = self.dists_fun(self.series, **self.dists_options)
        dists_cond = np.zeros(self._size_cond(len(series)))
        idx = 0
        for r in range(len(series) - 1):
            dists_cond[idx:idx + len(series) - r - 1] = dists[r, r + 1:]
            idx += len(series) - r - 1

        self.linkage = linkage(dists_cond, method=self.method, metric='euclidean')
```
Should there be a return in this function?

**Comment by wannesm** [comment]
The scipy linkage function does not directly return a clustering. How to get to a flat clustering depends on the goal of the user. This class is rather an example on how you can use other existing cluster algorithms.

**Comment by jmtatsch** [comment]
I just had a similar problem.
After cluster_idx = model3.fit(series) I expected cluster_idx to contain a linkage array that can be read with scipy's fcluster.
Fortunately the linkage array can easily be accessed like this in fcluster(model3.linkage, 2, criterion='maxclust') though returning it would be the more generally expected behavior.

Anyhow, thank you very much @wannesm  for building and supporting this useful piece of software!
