### ISSUE TITLE
What is happening with the dtw distance?

### ISSUE THREAD

**Issue by hazzehh** [wannesm/dtaidistance#8]
I was just comparing results with other dynamic time warping libraries and noticed significant differences in the dtw distances, despite similar paths. Am I missing something or is there an error somewhere in your distance calculation?

```` 
dist1,paths= dtw.warping_paths(s1,s2)
path = dtw.best_path(paths) 
print(dist1)

dist2 = 0
for [a, b] in path:
    dist2 += abs(s1[a]-s2[b])
print(dist2)
````

`dist1` and `dist2` are vastly different in my examples.

**Comment by wannesm** [comment]
This toolbox uses quadratic differences instead of absolute. Thus (a-b)**2 instead of abs(a-b).

**Comment by hazzehh** [comment]
@wannesm  Ahh, of course. Is there any particular reason reason why?

**Comment by wannesm** [comment]
It’s often used because it prefers many small deviations over a few large ones (but abs(a-b) is faster). It appears also to be the most popular one in papers. See for example the extensive work by Eamonn Keogh, http://www.cs.ucr.edu/%7Eeamonn/AAAI_2011_keogh.pdf and http://www.cs.unm.edu/~mueen/DTW.pdf .
