### ISSUE TITLE
DOC: https://dtaidistance.readthedocs.io/en/latest/usage/dtw.html

### ISSUE THREAD

**Issue by keithbriggs** [wannesm/dtaidistance#80]
There is a confusing change of terminology in this bit:

    DTW between set of series
    To compute the DTW distance measures between all sequences in a list of sequences

In python, a set is not a list.   And what is the difference between a series and a sequence?

**Comment by wannesm** [comment]
I understand the confusion.

The methods don't make a difference between the Python concepts list and sets, it only requires an iterable (although a list is typically preferred because you define the order explicitly).

In 'time series' literature the words sequence and series are often used interchangeably. From a dictionary point of view, I think this is indeed the case but from a mathematical point of view this would be 'sequence'.

**Comment by keithbriggs** [comment]
Ok, thanks.

Keith
